### ISSUE TITLE
Random Get Request

### ISSUE THREAD

**Issue by JosephMeli** [NERVEUML/Test-runner-webapp#6]
There's a Random Get request that fires and causes submit function to dump all contents of the form names into the URL

**Comment by ghost** [comment]
forms "submit" to an "action" using a "method". The contents are of the form, the submission is driven by a button or input with type=submit, the method is either GET or POST (if the form contents are in the URL it's a GET), and the action is the page itself by default. This is meant to allow easy server-side form processing.
What you want is either a non-submit button or some other way of preventing the form from actually being "submitted", all you want is to process it yourself in javascript.


All this web stuff is still centered around being able to do things simply, without javascript. Things like this are where that's most obvious.

**Comment by ghost** [comment]
I meant to catch this when we were paired, but it totally slipped my mind and in the moment we were focused on other stuff. Jon reminded me of it later.

**Comment by JosephMeli** [comment]
@mach327  None of the forms in my index.html or the buttons anywhere in the web app has a type of submit. All actions they perform are derived from the functions I have written.  Unless you're saying, all buttons cause this GET / POST action?

**Comment by ghost** [comment]
That's odd. Maybe they do. Try preventing default in your click handler, that ought to stop it.

**Comment by JosephMeli** [comment]
ummm. Closing this for now not sure why but it seems code that wrote fixed this issue and now have tested in both firefox and chrome and have now random data post in the url
